version: "3.3"

services:
  es:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.11.2"
    container_name: es
    environment:
      - node.name=es
      - cluster.name=blog-search-cluster
      # - cluster.initial_master_nodes=es
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  kib:
    image: docker.elastic.co/kibana/kibana:7.11.2
    container_name: kib
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: es:9200
      ELASTICSEARCH_HOSTS: http://es:9200
    networks:
      - elastic
  indexer:
    container_name: indexer
    build: ./indexer/
    command: tail -f /dev/null
    volumes:
      - ./indexer:/usr/src/app
    environment:
      ELASTICSEARCH_HOST: http://es:9200
    networks:
      - elastic

volumes:
  data:
    driver: local

networks:
  elastic:
    driver: bridge